image: gitpod/workspace-base

tasks:
  - name: install mamba
    init: |
      cd /workspace
      wget "https://github.com/conda-forge/miniforge/releases/download/24.3.0-0/Mambaforge-24.3.0-0-Linux-x86_64.sh"
      bash Mambaforge-24.3.0-0-Linux-x86_64.sh -b -p /workspace/mambaforge && rm Mambaforge-24.3.0-0-Linux-x86_64.sh

      /workspace/mambaforge/bin/mamba init bash
      source ${HOME}/.bashrc
      
      # set up conda evironment with R and needed packages
      mamba create -n gs -c conda-forge r-base r-argparse r-minpack.lm -y
      mamba activate gs
      mamba install -c bioconda kmc -y

      cd /workspace
      mkdir src bin && cd src # create directories for source code & binaries
      git clone https://github.com/thegenemyers/FastK
      cd FastK && make
      install -c FastK Fastrm Fastmv Fastcp Fastmerge Histex Tabex Profex Logex Vennex Symmex Haplex Homex Fastcat /workspace/bin/
    
      # install genomescope2 (both package and executible script)
      git clone https://github.com/tbenavi1/genomescope2.0
      R -e 'install.packages("genomescope2.0", repos=NULL, type="source")'
      install -c genomescope2.0/genomescope.R /workspace/bin

      # install genomeTelescope R package
      git clone https://github.com/KamilSJaron/GenomeTelescope
      R -e 'install.packages("GenomeTelescope", repos=NULL, type="source")'

      # download yeast data
      mkdir -p data && wget -P data https://sk13.cog.sanger.ac.uk/SRR3265401_{1,2}.fastq.gz

      gp sync-done bundle
    command: |
      cd /workspace
      /workspace/mambaforge/bin/mamba init bash
      source ${HOME}/.bashrc
      mamba activate gs

      export PATH=/workspace/bin:"$PATH"

vscode:
  extensions:
    - anwar.papyrus-pdf

workspaceLocation: "/workspace"
